"""
Django settings for blog_main project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from django.contrib.messages import constants as messages
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = os.path.join(BASE_DIR, 'static')

MESSAGE_TAGS = {
    messages.ERROR: "danger",  # thay error bằng danger
}
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o*j1*gwwo&vg*32ng@oo_c9rcr7s7i5049ck92y&8ef72sp07u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blogs',
    'django_ckeditor_5',
    'crispy_forms',
    'crispy_bootstrap4'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR /'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blogs.context_processors.categories_processor',
                'blogs.context_processors.youtube_channel_context',

            ],
        },
    },
]

WSGI_APPLICATION = 'blog_main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    STATIC_DIR 
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

YOUTUBE_API_KEY = "AIzaSyCB5g5djPGjEgWN2xjgmOvdNs861T4Vy18"

# Cấu hình đường dẫn cho các tệp phương tiện (media files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
CRISPY_TEMPLATE_PACK = 'bootstrap4'



CKEDITOR_5_FILE_BROWSER = 'filebrowser'  # nếu bạn muốn hỗ trợ quản lý file
CKEDITOR_5_UPLOAD_PATH = 'uploads/'  # thư mục lưu file upload
CKEDITOR_5_CONFIGS = {
    "default": {
        "language": "vi",
        "toolbar": [
            "heading", "|",
            "bold", "italic", "underline", "link", "|",
            "bulletedList", "numberedList", "|",
            "blockQuote", "insertTable", "imageUpload","htmlEmbed" , "|",
            "undo", "redo", "removeFormat", "|",
            "fontSize", "fontColor", "fontBackgroundColor"
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative", "toggleImageCaption",
                "imageStyle:inline", "imageStyle:side"
            ]
        },
        "table": {
            "contentToolbar": [
                "tableColumn", "tableRow", "mergeTableCells"
            ]
        },
        "heading": {
            "options": [
                {"model": "paragraph", "title": "Đoạn văn", "class": "ck-heading_paragraph"},
                {"model": "heading1", "view": "h1", "title": "Tiêu đề 1", "class": "ck-heading_heading1"},
                {"model": "heading2", "view": "h2", "title": "Tiêu đề 2", "class": "ck-heading_heading2"},
                {"model": "heading3", "view": "h3", "title": "Tiêu đề 3", "class": "ck-heading_heading3"},
            ]
        },
        "removePlugins": [],
        "extraPlugins": [],
    }
}



