# Generated by Django 5.2.1 on 2025-08-09 09:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Nội dung'),
        ),
    ]
