# Generated by Django 5.2.1 on 2025-08-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_subcategory_image_subcategory_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='subcategory',
        ),
    ]
