# Generated by Django 5.2.1 on 2025-08-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='label',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
