# Generated by Django 5.2.1 on 2025-09-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_category_icon_subcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='subcategory_icons/'),
        ),
    ]
