# Generated by Django 5.2.1 on 2025-09-24 09:06

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_childcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên quốc gia')),
                ('capital', models.CharField(max_length=100, verbose_name='Thủ đô')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Quốc kỳ')),
                ('geography', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Vị trí địa lý')),
                ('area', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Diện tích')),
                ('population', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Dân số')),
                ('language', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Ngôn ngữ chính')),
                ('government', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Chính thể')),
                ('economy', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Kinh tế')),
                ('currency', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Tiền tệ')),
                ('climate', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Khí hậu')),
                ('features', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Nét đặc trưng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('childcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='blogs.childcategory', verbose_name='Nhóm con')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
