# Generated by Django 5.2.1 on 2025-09-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='maps/', verbose_name='Bản đồ'),
        ),
    ]
