# Generated by Django 5.2.1 on 2025-09-24 11:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_country_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='geography',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Vị trí địa lý'),
        ),
    ]
