# Generated by Django 5.2.1 on 2025-09-24 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_country_geography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='features',
        ),
        migrations.CreateModel(
            name='DetailCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, null=True, upload_to='detail_backgrounds/', verbose_name='Background')),
                ('history', models.TextField(blank=True, null=True, verbose_name='Lịch sử')),
                ('geography', models.TextField(blank=True, null=True, verbose_name='Địa lý')),
                ('culture', models.TextField(blank=True, null=True, verbose_name='Văn hóa')),
                ('landmarks', models.TextField(blank=True, null=True, verbose_name='Địa danh')),
                ('famous_people', models.TextField(blank=True, null=True, verbose_name='Danh nhân')),
                ('others', models.TextField(blank=True, null=True, verbose_name='Khác')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('childcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_countries', to='blogs.childcategory', verbose_name='Child Category')),
            ],
            options={
                'verbose_name_plural': 'Detail Countries',
            },
        ),
    ]
