# Generated by Django 5.2.1 on 2025-09-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_remove_country_features_detailcountry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailCountry',
        ),
    ]
