# Generated by Django 5.2.1 on 2025-09-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_detailcountry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailCountry',
        ),
    ]
