# Generated by Django 5.2.1 on 2025-09-24 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_delete_detailcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('childcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_countries', to='blogs.childcategory', verbose_name='Child Category')),
            ],
            options={
                'verbose_name_plural': 'Detail Countries',
            },
        ),
    ]
