# Generated by Django 5.2.1 on 2025-09-25 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_detailcountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='blog',
            name='detail_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blogs.detailcountry', verbose_name='Detail Country'),
        ),
    ]
